build: off

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- echo "" | stack --no-terminal setup --resolver=nightly > nul

- cd as-dep-index
- echo "" | ..\stack --no-terminal build
- cd ..

- cd as-dep-local
- echo "" | ..\stack --no-terminal build
- cd ..

- cd as-target
- echo "" | ..\stack --no-terminal build
- cd ..

- cd from-snapshot
- echo "" | ..\stack --no-terminal build
- cd ..
