build: off

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- echo "" | stack --no-terminal setup --resolver=nightly-2018-05-23 > nul

- stack --resolver ghc-8.4.2 ghc print-sed-loc.hs
- .\print-sed-loc.exe
- stack --resolver ghc-8.4.2 exec .\print-sed-loc.exe
- stack --resolver nightly-2018-05-23 exec .\print-sed-loc.exe

- stack --resolver ghc-8.4.2 ghc build.hs
- .\build.exe
