build: off

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- echo "" | stack --no-terminal setup --resolver=nightly-2018-06-17 > nul

- stack --resolver ghc-8.4.3 ghc modified-sed.hs
- stack --resolver ghc-8.4.3 runghc move-sed.hs

- stack --resolver ghc-8.4.3 ghc build.hs

- .\build.exe

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

